export { default as BasicScene } from './BasicScene';
export { default as CubeScene } from './CubeScene';
export { default as Slide1Scene } from './Slide1Scene';
export { default as Slide4Scene } from './Slide4Scene';
export { default as Slide5Scene } from './Slide5Scene';
export { default as Slide8Scene } from './Slide8Scene';
export { default as Slide10Scene } from './Slide10Scene';
export { default as Slide15Scene } from './Slide15Scene';
export { default as Slide18Scene } from './Slide18Scene';
